/**
 * Journey + screen matrices from the full-stack suite (MVC-EPC-D-001 Lane D, D0).
 * Reads e2e-full/.results/results.json (Playwright JSON reporter) and writes:
 *   e2e/JOURNEYS.md      frozen journey -> test ids -> status
 *   ../product/SCREENS.md frozen screen catalogue -> route -> tests -> status
 * A journey or screen is PASS only when every tagged test passed in ALL four projects (ar/en x desktop/mobile).
 * Run: node e2e-full/report.mjs   (after `npx playwright test -c playwright.full.config.ts`)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const web = path.resolve(here, '..')
const root = path.resolve(web, '..')
const PROJECTS = ['ar-desktop', 'ar-mobile', 'en-desktop', 'en-mobile']
const JOURNEYS = [
  'J-00', ...Array.from({ length: 12 }, (_, i) => `J-O${i + 1}`), ...Array.from({ length: 9 }, (_, i) => `J-V${i + 1}`),
  ...Array.from({ length: 7 }, (_, i) => `J-P${i + 1}`), ...Array.from({ length: 8 }, (_, i) => `J-C${i + 1}`),
  ...Array.from({ length: 7 }, (_, i) => `J-A${i + 1}`), ...Array.from({ length: 6 }, (_, i) => `J-M${i + 1}`),
  'J-CHAIN-CLINIC', 'J-CHAIN-PHARMACY', 'J-CHAIN-MARKET',
]

const resultsFile = path.join(here, '.results', 'results.json')
const results = fs.existsSync(resultsFile) ? JSON.parse(fs.readFileSync(resultsFile, 'utf8')) : { suites: [] }
const tests = []                                      // { title, file, project, status }
const walk = (suite, file) => {
  for (const s of suite.suites ?? []) walk(s, s.file ?? file)
  for (const spec of suite.specs ?? []) for (const t of spec.tests ?? []) {
    const last = t.results?.[t.results.length - 1]
    tests.push({ title: spec.title, file: spec.file ?? file, project: t.projectName, status: last?.status ?? 'skipped' })
  }
}
for (const s of results.suites ?? []) walk(s, s.file)

const tagged = (re) => {
  const by = new Map()
  for (const t of tests) for (const m of t.title.matchAll(re)) {
    const e = by.get(m[1]) ?? new Map()
    const k = `${t.file} › ${t.title}`
    const p = e.get(k) ?? {}
    p[t.project] = t.status
    e.set(k, p)
    by.set(m[1], e)
  }
  return by
}
const verdict = (entry) => {
  if (!entry || entry.size === 0) return 'NO_TEST'
  for (const p of entry.values()) for (const proj of PROJECTS) if (p[proj] !== 'passed') return 'FAIL'
  return 'PASS'
}
const journeys = tagged(/\[(J-[A-Z]+-?[A-Z0-9]*)\]/g)
const screens = tagged(/@S:([A-Z]{2,3}-\d{2})/g)
const routes = fs.existsSync(path.join(here, 'screen-routes.json')) ? JSON.parse(fs.readFileSync(path.join(here, 'screen-routes.json'), 'utf8')) : {}

let jmd = '# Journey matrix (generated by petcare_web/e2e-full/report.mjs — do not edit)\n\n'
jmd += 'PASS = every tagged test passed in ar-desktop, ar-mobile, en-desktop and en-mobile against the full stack.\n\n'
jmd += '| Journey | Status | Tests |\n|---|---|---|\n'
for (const j of JOURNEYS) jmd += `| ${j} | ${verdict(journeys.get(j))} | ${[...(journeys.get(j)?.keys() ?? [])].join('<br>') || '—'} |\n`
const jPass = JOURNEYS.filter(j => verdict(journeys.get(j)) === 'PASS').length
jmd += `\nTOTAL ${JOURNEYS.length} · PASS ${jPass}\n`
fs.writeFileSync(path.join(web, 'e2e', 'JOURNEYS.md'), jmd)

const cat = JSON.parse(fs.readFileSync(path.join(root, 'product', 'screens.catalogue.json'), 'utf8')).screens
let smd = '# Screen catalogue — MVC-EPC-D-001 v1.5 (frozen, 107 screens). Status generated by petcare_web/e2e-full/report.mjs\n\n'
smd += 'PASS = the screen\'s journey tests passed in all four projects. Route from e2e-full/screen-routes.json.\n\n'
smd += '| Id | Surface | Screen | Route | Tests | Status |\n|---|---|---|---|---|---|\n'
for (const s of cat) smd += `| ${s.id} | ${s.surface} | ${s.screen} | ${routes[s.id] ?? '—'} | ${screens.get(s.id)?.size ?? 0} | ${verdict(screens.get(s.id))} |\n`
const sPass = cat.filter(s => verdict(screens.get(s.id)) === 'PASS').length
smd += `\nTOTAL ${cat.length} · PASS ${sPass}\n`
fs.writeFileSync(path.join(root, 'product', 'SCREENS.md'), smd)
console.log(`journeys ${jPass}/${JOURNEYS.length} PASS · screens ${sPass}/${cat.length} PASS · tests ${tests.length}`)
