/**
 * lib/strings.ts — Bilingual string registry (AR/EN)
 *
 * Used by LangProvider context. All UI strings live here so the
 * language toggle has a single authoritative source.
 */
export type Lang = 'ar' | 'en'

export const STRINGS = {
  nav: {
    brand:    { ar: 'VetiCare', en: 'VetiCare' },
    home:     { ar: 'الرئيسية',   en: 'Home' },
    clinics:  { ar: 'العيادات',    en: 'Clinics' },
    signIn:   { ar: 'تسجيل الدخول', en: 'Sign in' },
    signOut:  { ar: 'تسجيل الخروج', en: 'Sign out' },
  },
  home: {
    eyebrow:  { ar: 'منصة الرعاية البيطرية المحكومة', en: 'Governed veterinary platform' },
    h1:       { ar: 'صحة حيوانك الأليف،\nبعناية موثوقة ورقابة طبية كاملة',
                en: 'Clinical care, built for\naccountability from day one.' },
    sub:      { ar: 'VetiCare تربط الملّاك والأطباء والصيدليات تحت منصة موحّدة — كل إجراء موثّق، وكل وصفة قابلة للتتبع، وكل استشارة موقّعة.',
                en: 'VetiCare connects owners, vets, and pharmacies under a single governed platform — every action audited, every prescription traceable, every consultation signed.' },
    ctaSignIn:    { ar: 'تسجيل الدخول',  en: 'Sign in' },
    ctaOnboard:   { ar: 'تسجيل عيادة',   en: 'Clinic onboarding' },
    portalsLabel: { ar: 'البوابات',        en: 'Portals' },
    owner:    { ar: 'بوابة المالك',           en: 'Owner portal' },
    ownerSub: { ar: 'ملفات الحيوانات الأليفة، الجدول الصحي، حجز المواعيد، وإدارة الموافقات.',
                en: 'Pet profiles, health timeline, appointment booking, and consent management.' },
    ownerCta: { ar: 'فتح بوابة المالك',       en: 'Open owner portal' },
    vet:      { ar: 'بوابة الطبيب البيطري',   en: 'Vet portal' },
    vetSub:   { ar: 'قائمة الاستشارات، توقيع الملاحظات السريرية، توثيق الحالات، والإحالات الطارئة.',
                en: 'Consultation queue, clinical note sign-off, case documentation, and escalation.' },
    vetCta:   { ar: 'فتح بوابة الطبيب',       en: 'Open vet portal' },
    pharmacy:     { ar: 'بوابة الصيدلية',     en: 'Pharmacy portal' },
    pharmacySub:  { ar: 'قائمة الوصفات، سير عمل الصرف، السلامة الدوائية، وحالات السلسلة الباردة.',
                    en: 'Prescription queue, dispense workflow, safety and cold-chain states.' },
    pharmacyCta:  { ar: 'فتح بوابة الصيدلية', en: 'Open pharmacy portal' },
    admin:    { ar: 'بوابة الإدارة',           en: 'Admin portal' },
    adminSub: { ar: 'إدارة المستأجرين، الأدوار، تصدير الأدلة، وتتبع سجل المراجعة.',
                en: 'Tenant management, roles, evidence export, and audit visibility.' },
    adminCta: { ar: 'فتح بوابة الإدارة',       en: 'Open admin portal' },
    statusOk:      { ar: 'جميع الأنظمة تعمل',    en: 'All systems operational' },
    govActive:     { ar: 'الحوكمة المغلقة فعّالة', en: 'Fail-closed governance active' },
    auditLive:     { ar: 'سجل المراجعة نشط',       en: 'Audit chain live' },
    pilotPhase:    { ar: 'مرحلة التجريب',           en: 'Pilot phase' },
  },
  onboarding: {
    kicker:   { ar: 'برنامج التجريب',     en: 'Pilot programme' },
    title:    { ar: 'تسجيل العيادات',     en: 'Clinic onboarding' },
    intro:    { ar: 'VetiCare في مرحلة تجريب محكوم. يتم تسجيل العيادات بشكل فردي مع التحقق الكامل من الحوكمة قبل منح أي صلاحية وصول.',
                en: 'VetiCare is in a controlled pilot phase. Clinics are onboarded individually with full governance verification before any system access is granted.' },
    step1:    { ar: 'الخطوة 1', en: 'Step 1' },
    step1t:   { ar: 'التحقق من الأهلية', en: 'Eligibility check' },
    step1d:   { ar: 'يُشترط توفر سجل تجاري ساري، وأطباء بيطريون مرخّصون، وموقع عيادة موثّق قبل بدء عملية التسجيل.',
                en: 'Valid commercial registration, licensed vets on staff, and a verified clinic location are required before onboarding begins.' },
    step2:    { ar: 'الخطوة 2', en: 'Step 2' },
    step2t:   { ar: 'التحقق من الهوية', en: 'Identity verification' },
    step2d:   { ar: 'يتم التحقق من هوية كل طبيب بيطري عبر سجل التراخيص الوطني. لا يُمنح الوصول حتى اكتمال التحقق.',
                en: 'Each vet is verified against the national licensing registry. No system access is granted until verification is complete.' },
    step3:    { ar: 'الخطوة 3', en: 'Step 3' },
    step3t:   { ar: 'إعداد الحساب', en: 'Account provisioning' },
    step3d:   { ar: 'تُسنَد الأدوار عبر بوابة الإدارة. جميع أحداث الإعداد مسجّلة في سجل المراجعة ومرتبطة بمعرّف ارتباط.',
                en: 'Roles are assigned via the admin portal. All provisioning events are audit-logged and tied to a correlation ID.' },
    step4:    { ar: 'الخطوة 4', en: 'Step 4' },
    step4t:   { ar: 'تفعيل التجريب', en: 'Pilot activation' },
    step4d:   { ar: 'بعد التفعيل، تصبح لوحة تحكم العيادة وقائمة الاستشارات وسير عمل الوصفات متاحةً تحت إطار العمل المحكوم.',
                en: 'Once active, the clinic dashboard, consultation queue, and prescription workflow are accessible under governed operation.' },
    ctaTitle: { ar: 'هل أنت مستعد للانضمام للتجريب؟', en: 'Ready to join the pilot?' },
    ctaSub:   { ar: 'تواصل مع فريق التسجيل مع بيانات تسجيل عيادتك.', en: 'Reach out to the onboarding team with your clinic registration details.' },
    ctaBtn:   { ar: 'التقدم للوصول التجريبي', en: 'Apply for pilot access' },
  },
  signin: {
    kicker:       { ar: 'VetiCare',           en: 'VetiCare' },
    title:        { ar: 'تسجيل الدخول إلى حسابك', en: 'Sign in to your account' },
    sub:          { ar: 'أدخل بياناتك للوصول إلى منصة VetiCare', en: 'Enter your credentials to access VetiCare' },
    emailLabel:   { ar: 'البريد الإلكتروني',  en: 'Email' },
    passwordLabel:{ ar: 'كلمة المرور',         en: 'Password' },
    submit:       { ar: 'تسجيل الدخول',        en: 'Sign in' },
    submitting:   { ar: 'جارٍ تسجيل الدخول…', en: 'Signing in…' },
    noSelfReg:    { ar: 'الوصول بدعوة فقط. إذا كان لديك رمز دعوة من فريق التجريب، سجّل حسابك.',
                    en: 'Access is invite-only. If you have a pilot invite code, register your account.' },
    registerCta:  { ar: 'لديك رمز دعوة؟ سجّل الآن',
                    en: 'Have an invite code? Register' },
    backHome:     { ar: '→ العودة للرئيسية',   en: '← Back to home' },
    errInvalid:   { ar: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
                    en: 'Invalid email or password.' },
    errInactive:  { ar: 'هذا الحساب غير نشط. تواصل مع المسؤول.',
                    en: 'This account is inactive. Contact your administrator.' },
    errFailed:    { ar: 'فشل تسجيل الدخول. حاول مرة أخرى.',
                    en: 'Sign-in failed. Try again.' },
    errNetwork:   { ar: 'تعذّر الوصول إلى الخادم. تحقق من اتصالك وحاول مرة أخرى.',
                    en: 'Could not reach the server. Check your connection and try again.' },
  },
  unauthorized: {
    title:        { ar: 'وصول مقيّد',          en: 'Access restricted' },
    subFrom:      { ar: 'الصفحة {from} تتطلب دوراً محدداً للوصول.',
                    en: 'The page {from} requires a specific role to access.' },
    subGeneric:   { ar: 'ليس لديك صلاحية لعرض هذه الصفحة.',
                    en: 'You do not have permission to view this page.' },
    requiredRole: { ar: 'الدور المطلوب:',       en: 'Required role:' },
    body:         { ar: 'إذا كان لديك حساب، سجّل الدخول وسيتم تعيين دورك تلقائياً.',
                    en: 'If you have an account, sign in and your role will be assigned automatically.' },
    ctaSignIn:    { ar: 'تسجيل الدخول',         en: 'Sign in' },
    ctaHome:      { ar: 'العودة للرئيسية',       en: 'Back to home' },
    roles: {
      owner:    { ar: 'مالك حيوان أليف',    en: 'Pet Owner' },
      vet:      { ar: 'طبيب بيطري مرخّص',  en: 'Licensed Veterinarian' },
      pharmacy: { ar: 'مشغّل صيدلية',       en: 'Pharmacy Operator' },
      admin:    { ar: 'مدير المنصة',         en: 'Platform Admin' },
    },
  },
  onboardingHub: {
    kicker:       { ar: 'برنامج التجريب',          en: 'Pilot programme' },
    title:        { ar: 'انضم إلى VetiCare',        en: 'Join VetiCare' },
    intro:        { ar: 'اختر نوع حسابك للبدء في عملية التسجيل.',
                    en: 'Choose your account type to begin the onboarding process.' },
    clinicTitle:  { ar: 'عيادة / طبيب بيطري',       en: 'Clinic / Veterinarian' },
    clinicSub:    { ar: 'عيادات بيطرية وأطباء مرخّصون يقدمون خدمات الرعاية والاستشارة.',
                    en: 'Veterinary clinics and licensed vets providing care and consultation services.' },
    clinicCta:    { ar: 'تسجيل عيادة',               en: 'Register a clinic' },
    pharmacyTitle:{ ar: 'صيدلية بيطرية',             en: 'Veterinary Pharmacy' },
    pharmacySub:  { ar: 'صيدليات تصرف الأدوية البيطرية وتتتبع المخزون وفق متطلبات هيئة الغذاء والدواء.',
                    en: 'Pharmacies dispensing veterinary medications with full SFDA batch tracking.' },
    pharmacyCta:  { ar: 'تسجيل صيدلية',              en: 'Register a pharmacy' },
  },
  owner: {
    kicker:       { ar: 'بوابة المالك',            en: 'Owner portal' },
    title:        { ar: 'حيواناتي الأليفة',        en: 'My pets' },
    auditActive:  { ar: 'التدقيق نشط',              en: 'Audit active' },
    petProfileTitle:    { ar: 'ملف الحيوان الأليف', en: 'Pet profile' },
    petProfileSub:      { ar: 'الهوية، النوع، العمر، الحساسية، التطعيمات، وبيانات الشريحة.',
                          en: 'Identity, species, age, allergies, vaccinations, and microchip data.' },
    petProfileEmpty:    { ar: 'لا توجد حيوانات مسجلة بعد',
                          en: 'No pets registered yet' },
    addPet:             { ar: 'إضافة حيوان أليف',    en: 'Add a pet' },
    timelineTitle:      { ar: 'الجدول الصحي',         en: 'Health timeline' },
    timelineSub:        { ar: 'الزيارات، الوصفات، نتائج المختبر، والأحداث السريرية بالترتيب.',
                          en: 'Visits, prescriptions, lab results, and clinical events in order.' },
    timelineEmpty:      { ar: 'لا توجد سجلات بعد',  en: 'No records yet' },
    appointmentsTitle:  { ar: 'المواعيد',              en: 'Appointments' },
    appointmentsSub:    { ar: 'حجز وإعادة جدولة وإلغاء مع تتبع تدقيق كامل لكل إجراء.',
                          en: 'Book, reschedule, and cancel with full audit trace on each action.' },
    appointmentsBook:   { ar: 'حجز موعد',             en: 'Book appointment' },
    consentTitle:       { ar: 'الموافقة',              en: 'Consent' },
    consentSub:         { ar: 'منح وسحب موافقة العلاج. كل تغيير مسجل بشكل غير قابل للتعديل.',
                          en: 'Capture and revoke treatment consent. Every change is immutably logged.' },
    consentEmpty:       { ar: 'لا توجد موافقات نشطة', en: 'No active consents' },
    governanceNote:     { ar: 'جميع الإجراءات في هذه البوابة محكومة ومتتبعة. تسجيل الخروج يُلغي جلستك النشطة.',
                          en: 'All actions in this portal are governed and audit-traced. Signing out revokes your active session.' },
    emergencyCta:       { ar: 'حالة طارئة',           en: 'Emergency' },
    emergencyHint:      { ar: 'هل حيوانك في حالة طارئة؟ اضغط للحصول على إرشادات فورية.',
                          en: 'Is your pet in an emergency? Tap for immediate guidance.' },
  },
  emergency: {
    title:        { ar: 'حالة طارئة — إرشادات فورية',
                    en: 'Emergency — immediate guidance' },
    sub:          { ar: 'هذه إرشادات أولية فقط. الطبيب البيطري المرخّص هو المرجع السريري النهائي.',
                    en: 'These are first-aid guidance only. The licensed veterinarian remains the clinical decision authority.' },
    speciesLabel: { ar: 'نوع الحيوان',                en: 'Species' },
    speciesDog:   { ar: 'كلب',                          en: 'Dog' },
    speciesCat:   { ar: 'قطة',                          en: 'Cat' },
    speciesBird:  { ar: 'طائر',                         en: 'Bird' },
    symptomsLabel:{ ar: 'الأعراض الملاحظة',          en: 'Observed symptoms' },
    evaluateCta:  { ar: 'تقييم الحالة',                en: 'Evaluate' },
    backToOwner:  { ar: '→ العودة إلى بوابة المالك',
                    en: '← Back to owner portal' },
    severityCriticalBanner: { ar: '🚑 حالة حرجة — اتصل بالطبيب البيطري الطارئ فوراً',
                              en: '🚑 Critical — contact an emergency vet immediately' },
    severityUrgentBanner:   { ar: '⚠️ حالة عاجلة — حدد موعداً عاجلاً مع الطبيب البيطري',
                              en: '⚠️ Urgent — book an urgent veterinary consult' },
    severityRoutineBanner:  { ar: 'لا توجد علامات إنذار حالياً — راقب حيوانك وحدد موعداً عند الحاجة',
                              en: 'No red-flag symptoms detected — monitor your pet and book a consult if needed' },
    triggeredLabel:        { ar: 'العلامات التي تم رصدها',
                             en: 'Triggered red flags' },
    urgentContactLabel:    { ar: 'جهة الاتصال للطوارئ',
                             en: 'Urgent contact' },
    urgentContactBody:     { ar: 'تواصل مع عيادتك البيطرية المسجّلة، أو اتصل بأقرب مستشفى بيطري للطوارئ. الفريق سيوجّهك للخطوات التالية.',
                             en: 'Contact your registered veterinary clinic, or call the nearest emergency veterinary hospital. The team will direct you on next steps.' },
    noQueueNote:           { ar: 'ملاحظة: هذه إرشادات عرض فقط. لا يتم توجيه الحالات تلقائياً إلى الأطباء البيطريين عبر هذه المنصة في مرحلة التجريب.',
                             en: 'Note: this is display-only guidance. The pilot does not route cases automatically to veterinarians on the platform.' },
  },
  firstRun: {
    welcomeKicker:  { ar: 'مرحباً بك في VetiCare', en: 'Welcome to VetiCare' },
    welcomeTitle:   { ar: 'دعنا نبدأ', en: 'Let’s get started' },
    welcomeSub:     { ar: 'جولة قصيرة لمساعدتك في الإعداد. يمكنك تخطّيها في أي وقت.',
                      en: 'A short walkthrough to help you set up. You can skip at any time.' },
    skip:           { ar: 'تخطّي', en: 'Skip' },
    next:           { ar: 'التالي', en: 'Next' },
    done:           { ar: 'إنهاء', en: 'Finish' },
    step1Badge:     { ar: 'الخطوة 1', en: 'Step 1' },
    step1Title:     { ar: 'ملفك مكتمل',
                      en: 'Your profile is ready' },
    step1Body:      { ar: 'تم إنشاء حسابك. كل إجراء في هذه البوابة مسجّل ومحكوم.',
                      en: 'Your account is created. Every action in this portal is audit-logged and governed.' },
    step2Badge:     { ar: 'الخطوة 2', en: 'Step 2' },
    step2Title:     { ar: 'أضف أول حيوان أليف',
                      en: 'Add your first pet' },
    step2Body:      { ar: 'سجّل ملف حيوانك (الاسم، النوع، العمر). هذا أول إجراء حقيقي ضمن المنصة.',
                      en: 'Register your pet’s profile (name, species, age). This is your first real action on the platform.' },
    step3Badge:     { ar: 'الخطوة 3', en: 'Step 3' },
    step3Title:     { ar: 'في الطوارئ، اضغط زر الحالة الطارئة',
                      en: 'In emergencies, tap the Emergency button' },
    step3Body:      { ar: 'يظهر زر الحالة الطارئة في رأس البوابة. يعرض إرشادات فورية، ولا يستبدل تقييم الطبيب البيطري.',
                      en: 'The Emergency button is at the top of the portal. It surfaces immediate guidance; it does not replace your vet’s assessment.' },
    primaryActionCta: { ar: 'إضافة أول حيوان أليف',
                        en: 'Add your first pet' },
    secondaryActionCta: { ar: 'تصفح البوابة أولاً',
                          en: 'Browse the portal first' },
  },
  register: {
    kicker:       { ar: 'Maqaleed Vet by VetiCare',
                    en: 'Maqaleed Vet by VetiCare' },
    title:        { ar: 'إنشاء حساب التجريب',
                    en: 'Create your pilot account' },
    sub:          { ar: 'التسجيل محكوم برمز دعوة من فريق التجريب. لا يتوفر تسجيل عام.',
                    en: 'Registration is invite-gated. There is no public registration path.' },
    inviteOnlyBadge: { ar: 'دعوة فقط — مرحلة التجريب',
                       en: 'Invite only — pilot phase' },
    nameLabel:    { ar: 'الاسم الكامل',          en: 'Full name' },
    emailLabel:   { ar: 'البريد الإلكتروني',     en: 'Email' },
    phoneLabel:   { ar: 'رقم الهاتف (اختياري)',  en: 'Phone number (optional)' },
    inviteLabel:  { ar: 'رمز الدعوة',             en: 'Invite code' },
    passwordLabel:{ ar: 'كلمة المرور',            en: 'Password' },
    roleLabel:    { ar: 'نوع الحساب',             en: 'Account type' },
    roleOwner:    { ar: 'مالك حيوان أليف',       en: 'Pet owner' },
    roleVet:      { ar: 'طبيب بيطري مرخّص',     en: 'Licensed veterinarian' },
    submit:       { ar: 'إنشاء الحساب',          en: 'Create account' },
    submitting:   { ar: 'جارٍ إنشاء الحساب…',   en: 'Creating account…' },
    haveAccount:  { ar: 'لديك حساب؟ تسجيل الدخول',
                    en: 'Have an account? Sign in' },
    backHome:     { ar: '→ العودة للرئيسية',     en: '← Back to home' },
    errInvalidInvite:  { ar: 'رمز الدعوة غير صالح أو مستخدم.',
                         en: 'Invite code is invalid or already used.' },
    errInviteExpired:  { ar: 'انتهت صلاحية رمز الدعوة.',
                         en: 'Invite code has expired.' },
    errRoleMismatch:   { ar: 'رمز الدعوة لا يطابق نوع الحساب المحدد.',
                         en: 'Invite code does not match the selected account type.' },
    errEmailExists:    { ar: 'البريد الإلكتروني مسجّل بالفعل.',
                         en: 'Email is already registered.' },
    errFailed:    { ar: 'تعذّر إنشاء الحساب. حاول مرة أخرى.',
                    en: 'Could not create account. Try again.' },
    errNetwork:   { ar: 'تعذّر الوصول إلى الخادم. تحقق من اتصالك.',
                    en: 'Could not reach the server. Check your connection.' },
    pdpaNotice:   { ar: 'بإنشاء حساب فإنك توافق على معالجة بياناتك وفق سياسة الخصوصية. إقامة البيانات: قيد التأكيد. تقييم أثر الخصوصية (DPIA): قيد التنفيذ.',
                    en: 'By creating an account you consent to processing per the Privacy Notice. Data residency: pending confirmation. DPIA: in progress.' },
  },
  pharmacyOnboarding: {
    kicker:    { ar: 'تسجيل الصيدليات',              en: 'Pharmacy registration' },
    title:     { ar: 'تسجيل صيدليتك في VetiCare',   en: 'Register your pharmacy on VetiCare' },
    intro:     { ar: 'تُنضم الصيدليات البيطرية بعد التحقق من ترخيص هيئة الغذاء والدواء وتسجيل المخزون الأولي.',
                 en: 'Veterinary pharmacies are onboarded after SFDA licence verification and initial inventory registration.' },
    step1:     { ar: 'الخطوة 1', en: 'Step 1' },
    step1t:    { ar: 'التحقق من السجل التجاري', en: 'Commercial registration' },
    step1d:    { ar: 'سجل تجاري ساري للصيدلية البيطرية مطلوب قبل بدء عملية التسجيل.',
                 en: 'A valid commercial registration for the veterinary pharmacy is required before onboarding begins.' },
    step2:     { ar: 'الخطوة 2', en: 'Step 2' },
    step2t:    { ar: 'ترخيص هيئة الغذاء والدواء', en: 'SFDA licence verification' },
    step2d:    { ar: 'يتم التحقق من رقم ترخيص هيئة الغذاء والدواء وصلاحيته. لا يُمنح الوصول حتى اكتمال التحقق.',
                 en: 'Your SFDA pharmacy licence number and validity are verified. No access is granted until verification is complete.' },
    step3:     { ar: 'الخطوة 3', en: 'Step 3' },
    step3t:    { ar: 'التحقق من الموقع', en: 'Location verification' },
    step3d:    { ar: 'يتم التحقق من عنوان الصيدلية ومطابقته للسجل التجاري وترخيص هيئة الغذاء والدواء.',
                 en: 'The pharmacy address is verified against the commercial registration and SFDA licence on file.' },
    step4:     { ar: 'الخطوة 4', en: 'Step 4' },
    step4t:    { ar: 'تفعيل الحساب والمخزون', en: 'Account & inventory activation' },
    step4d:    { ar: 'بعد التفعيل، تصبح بوابة الصيدلية ومخزون الأدوية وسير عمل الصرف متاحةً تحت إطار العمل المحكوم.',
                 en: 'Once active, the pharmacy portal, medication inventory, and dispense workflow are accessible under governed operation.' },
    ctaTitle:  { ar: 'هل أنت مستعد للانضمام؟',         en: 'Ready to join?' },
    ctaSub:    { ar: 'تواصل مع فريق التسجيل مع بيانات ترخيص صيدليتك.',
                 en: 'Reach out to the onboarding team with your pharmacy licence details.' },
    ctaBtn:    { ar: 'التقدم للوصول التجريبي',           en: 'Apply for pilot access' },
    backLink:  { ar: '→ العودة لصفحة التسجيل',           en: '← Back to onboarding' },
  },
} as const
