/**
 * lib/strings.ts — Bilingual string registry (AR/EN)
 *
 * Used by LangProvider context. All UI strings live here so the
 * language toggle has a single authoritative source.
 */
export type Lang = 'ar' | 'en'

export const STRINGS = {
  nav: {
    brand:    { ar: 'VetiCare', en: 'VetiCare' },
    home:     { ar: 'الرئيسية',   en: 'Home' },
    clinics:  { ar: 'العيادات',    en: 'Clinics' },
    signIn:   { ar: 'تسجيل الدخول', en: 'Sign in' },
    signOut:  { ar: 'تسجيل الخروج', en: 'Sign out' },
  },
  home: {
    eyebrow:  { ar: 'منصة الرعاية البيطرية المحكومة', en: 'Governed veterinary platform' },
    h1:       { ar: 'صحة حيوانك الأليف،\nبعناية موثوقة ورقابة طبية كاملة',
                en: 'Clinical care, built for\naccountability from day one.' },
    sub:      { ar: 'VetiCare تربط الملّاك والأطباء والصيدليات تحت منصة موحّدة — كل إجراء موثّق، وكل وصفة قابلة للتتبع، وكل استشارة موقّعة.',
                en: 'VetiCare connects owners, vets, and pharmacies under a single governed platform — every action audited, every prescription traceable, every consultation signed.' },
    ctaSignIn:    { ar: 'تسجيل الدخول',  en: 'Sign in' },
    ctaOnboard:   { ar: 'تسجيل عيادة',   en: 'Clinic onboarding' },
    portalsLabel: { ar: 'البوابات',        en: 'Portals' },
    owner:    { ar: 'بوابة المالك',           en: 'Owner portal' },
    ownerSub: { ar: 'ملفات الحيوانات الأليفة، الجدول الصحي، حجز المواعيد، وإدارة الموافقات.',
                en: 'Pet profiles, health timeline, appointment booking, and consent management.' },
    ownerCta: { ar: 'فتح بوابة المالك',       en: 'Open owner portal' },
    vet:      { ar: 'بوابة الطبيب البيطري',   en: 'Vet portal' },
    vetSub:   { ar: 'قائمة الاستشارات، توقيع الملاحظات السريرية، توثيق الحالات، والإحالات الطارئة.',
                en: 'Consultation queue, clinical note sign-off, case documentation, and escalation.' },
    vetCta:   { ar: 'فتح بوابة الطبيب',       en: 'Open vet portal' },
    pharmacy:     { ar: 'بوابة الصيدلية',     en: 'Pharmacy portal' },
    pharmacySub:  { ar: 'قائمة الوصفات، سير عمل الصرف، السلامة الدوائية، وحالات السلسلة الباردة.',
                    en: 'Prescription queue, dispense workflow, safety and cold-chain states.' },
    pharmacyCta:  { ar: 'فتح بوابة الصيدلية', en: 'Open pharmacy portal' },
    admin:    { ar: 'بوابة الإدارة',           en: 'Admin portal' },
    adminSub: { ar: 'إدارة المستأجرين، الأدوار، تصدير الأدلة، وتتبع سجل المراجعة.',
                en: 'Tenant management, roles, evidence export, and audit visibility.' },
    adminCta: { ar: 'فتح بوابة الإدارة',       en: 'Open admin portal' },
    statusOk:      { ar: 'جميع الأنظمة تعمل',    en: 'All systems operational' },
    govActive:     { ar: 'الحوكمة المغلقة فعّالة', en: 'Fail-closed governance active' },
    auditLive:     { ar: 'سجل المراجعة نشط',       en: 'Audit chain live' },
    pilotPhase:    { ar: 'مرحلة التجريب',           en: 'Pilot phase' },
  },
  onboarding: {
    kicker:   { ar: 'برنامج التجريب',     en: 'Pilot programme' },
    title:    { ar: 'تسجيل العيادات',     en: 'Clinic onboarding' },
    intro:    { ar: 'VetiCare في مرحلة تجريب محكوم. يتم تسجيل العيادات بشكل فردي مع التحقق الكامل من الحوكمة قبل منح أي صلاحية وصول.',
                en: 'VetiCare is in a controlled pilot phase. Clinics are onboarded individually with full governance verification before any system access is granted.' },
    step1:    { ar: 'الخطوة 1', en: 'Step 1' },
    step1t:   { ar: 'التحقق من الأهلية', en: 'Eligibility check' },
    step1d:   { ar: 'يُشترط توفر سجل تجاري ساري، وأطباء بيطريون مرخّصون، وموقع عيادة موثّق قبل بدء عملية التسجيل.',
                en: 'Valid commercial registration, licensed vets on staff, and a verified clinic location are required before onboarding begins.' },
    step2:    { ar: 'الخطوة 2', en: 'Step 2' },
    step2t:   { ar: 'التحقق من الهوية', en: 'Identity verification' },
    step2d:   { ar: 'يتم التحقق من هوية كل طبيب بيطري عبر سجل التراخيص الوطني. لا يُمنح الوصول حتى اكتمال التحقق.',
                en: 'Each vet is verified against the national licensing registry. No system access is granted until verification is complete.' },
    step3:    { ar: 'الخطوة 3', en: 'Step 3' },
    step3t:   { ar: 'إعداد الحساب', en: 'Account provisioning' },
    step3d:   { ar: 'تُسنَد الأدوار عبر بوابة الإدارة. جميع أحداث الإعداد مسجّلة في سجل المراجعة ومرتبطة بمعرّف ارتباط.',
                en: 'Roles are assigned via the admin portal. All provisioning events are audit-logged and tied to a correlation ID.' },
    step4:    { ar: 'الخطوة 4', en: 'Step 4' },
    step4t:   { ar: 'تفعيل التجريب', en: 'Pilot activation' },
    step4d:   { ar: 'بعد التفعيل، تصبح لوحة تحكم العيادة وقائمة الاستشارات وسير عمل الوصفات متاحةً تحت إطار العمل المحكوم.',
                en: 'Once active, the clinic dashboard, consultation queue, and prescription workflow are accessible under governed operation.' },
    ctaTitle: { ar: 'هل أنت مستعد للانضمام للتجريب؟', en: 'Ready to join the pilot?' },
    ctaSub:   { ar: 'تواصل مع فريق التسجيل مع بيانات تسجيل عيادتك.', en: 'Reach out to the onboarding team with your clinic registration details.' },
    ctaBtn:   { ar: 'التقدم للوصول التجريبي', en: 'Apply for pilot access' },
  },
  signin: {
    kicker:       { ar: 'VetiCare',           en: 'VetiCare' },
    title:        { ar: 'تسجيل الدخول إلى حسابك', en: 'Sign in to your account' },
    sub:          { ar: 'أدخل بياناتك للوصول إلى منصة VetiCare', en: 'Enter your credentials to access VetiCare' },
    emailLabel:   { ar: 'البريد الإلكتروني',  en: 'Email' },
    passwordLabel:{ ar: 'كلمة المرور',         en: 'Password' },
    submit:       { ar: 'تسجيل الدخول',        en: 'Sign in' },
    submitting:   { ar: 'جارٍ تسجيل الدخول…', en: 'Signing in…' },
    noSelfReg:    { ar: 'لا يوجد تسجيل ذاتي. تواصل مع مسؤول التجريب للحصول على صلاحية الوصول.',
                    en: 'No self-registration. Contact your pilot administrator for access.' },
    backHome:     { ar: '→ العودة للرئيسية',   en: '← Back to home' },
    errInvalid:   { ar: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
                    en: 'Invalid email or password.' },
    errInactive:  { ar: 'هذا الحساب غير نشط. تواصل مع المسؤول.',
                    en: 'This account is inactive. Contact your administrator.' },
    errFailed:    { ar: 'فشل تسجيل الدخول. حاول مرة أخرى.',
                    en: 'Sign-in failed. Try again.' },
    errNetwork:   { ar: 'تعذّر الوصول إلى الخادم. تحقق من اتصالك وحاول مرة أخرى.',
                    en: 'Could not reach the server. Check your connection and try again.' },
  },
  unauthorized: {
    title:        { ar: 'وصول مقيّد',          en: 'Access restricted' },
    subFrom:      { ar: 'الصفحة {from} تتطلب دوراً محدداً للوصول.',
                    en: 'The page {from} requires a specific role to access.' },
    subGeneric:   { ar: 'ليس لديك صلاحية لعرض هذه الصفحة.',
                    en: 'You do not have permission to view this page.' },
    requiredRole: { ar: 'الدور المطلوب:',       en: 'Required role:' },
    body:         { ar: 'إذا كان لديك حساب، سجّل الدخول وسيتم تعيين دورك تلقائياً.',
                    en: 'If you have an account, sign in and your role will be assigned automatically.' },
    ctaSignIn:    { ar: 'تسجيل الدخول',         en: 'Sign in' },
    ctaHome:      { ar: 'العودة للرئيسية',       en: 'Back to home' },
    roles: {
      owner:    { ar: 'مالك حيوان أليف',    en: 'Pet Owner' },
      vet:      { ar: 'طبيب بيطري مرخّص',  en: 'Licensed Veterinarian' },
      pharmacy: { ar: 'مشغّل صيدلية',       en: 'Pharmacy Operator' },
      admin:    { ar: 'مدير المنصة',         en: 'Platform Admin' },
    },
  },
} as const
