"""Where a prescription's bytes live, and what may be stored at all.

Option A §5. The metadata row is in `prescription_document` (migration 0036);
this module is the object side of it.

## The production store is NOT bound, and says so

`ProductionObjectStore` exists as an interface and raises. It is written that
way on purpose: a module that silently fell back to the local directory when no
object store was configured would make a deployment look complete, serve
uploads successfully, and lose every one of them on the next container replace.
That is the fallback argument `persistence.py` makes for the database, and the
failure mode is identical — a clean health check over a store nobody can read
twice. Binding a production object store requires a provider credential and is
`GATE_CREDENTIAL_ENTRY`; it is not done here.

## Path traversal is not defended against, it is unrepresentable

`storage_key` is generated by this module from a UUID. The caller's filename is
recorded as metadata and never joined to a path, so `../../etc/passwd` and
`x.pdf` reach exactly the same code and land in exactly the same place. A
sanitiser over a caller-chosen path would be a control that has to be right
every time; a server-generated key is one that cannot be wrong.

The resolved path is still re-checked against the root before any write or read.
Belt and braces is cheap here, and the check catches a future edit that makes
the key caller-influenced without noticing.
"""
from __future__ import annotations

import hashlib
import os
import uuid
from pathlib import Path
from typing import Protocol

#: What a prescription attachment may be. An allowlist, because the question
#: "is this dangerous?" has no reliable negative answer — and because the set of
#: things a clinic actually attaches is small and known.
#:
#: No `text/html` and no `image/svg+xml`: both execute script in a browser, and
#: an attachment that runs script is stored XSS against whoever opens it next.
ALLOWED_CONTENT_TYPES: frozenset[str] = frozenset({
    "application/pdf",
    "image/jpeg",
    "image/png",
    "image/heic",
})

#: 15 MiB. A phone photograph of a paper prescription is comfortably inside it.
MAX_DOCUMENT_BYTES = 15 * 1024 * 1024

#: What the bytes are served AS, regardless of what they were uploaded as.
#:
#: Downloads are forced. A stored object rendered inline is executed by the
#: browser in the application's origin if the type is ever wrong, and the type
#: is exactly the thing an attacker controls. `application/octet-stream` plus
#: `Content-Disposition: attachment` means a mislabelled file is downloaded, not
#: run.
SERVED_CONTENT_TYPE = "application/octet-stream"


class DocumentRejected(Exception):
    """The upload is not something this store will hold."""


class ObjectStoreUnavailable(Exception):
    """The configured store cannot be reached. Never downgraded to a fallback."""


def validate_upload(*, content_type: str, payload: bytes) -> None:
    """Everything checked BEFORE a prescription row is touched.

    Ordered deliberately: nothing about the prescription changes until the
    payload is known to be storable, so a rejected upload cannot leave a
    prescription referencing a document that was never written (§5's
    "upload failure does not create an inconsistent prescription state").
    """
    if not payload:
        raise DocumentRejected("an empty document is not a prescription")
    if len(payload) > MAX_DOCUMENT_BYTES:
        raise DocumentRejected(
            f"document is {len(payload)} bytes; the limit is "
            f"{MAX_DOCUMENT_BYTES}"
        )
    normalised = (content_type or "").split(";")[0].strip().lower()
    if normalised not in ALLOWED_CONTENT_TYPES:
        raise DocumentRejected(
            f"content type {content_type!r} is not an accepted prescription "
            f"attachment (accepted: {sorted(ALLOWED_CONTENT_TYPES)})"
        )


def new_storage_key(*, tenant_id: str, prescription_id: str) -> str:
    """A server-generated key. No caller input reaches it.

    The tenant is a PREFIX rather than the whole name so that a listing of one
    tenant's objects is possible without reading another's, and a key alone
    still cannot be guessed from a prescription id — the UUID is the entropy.
    """
    safe_tenant = uuid.uuid5(uuid.NAMESPACE_URL, f"tenant:{tenant_id}").hex
    return f"{safe_tenant}/{uuid.uuid4().hex}"


def sha256_hex(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


class DocumentStore(Protocol):
    def put(self, storage_key: str, payload: bytes) -> None: ...
    def get(self, storage_key: str) -> bytes: ...


class LocalFilesystemDocumentStore:
    """The non-production adapter. A directory, and nothing else.

    This is not a production object store and is not presented as one: it is
    node-local, so two instances do not see each other's uploads. That is
    acceptable for a single-node pilot rehearsal and unacceptable for
    production, which is why the production class below refuses rather than
    inheriting from this one.
    """

    def __init__(self, root: str | os.PathLike[str]) -> None:
        self._root = Path(root).resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, storage_key: str) -> Path:
        candidate = (self._root / storage_key).resolve()
        # The key is server-generated, so this cannot currently fail. It is
        # here so that it WOULD fail if a future edit let a caller influence the
        # key — the point at which the property stops being structural.
        if not candidate.is_relative_to(self._root):
            raise DocumentRejected(
                f"storage key {storage_key!r} resolves outside the document root"
            )
        return candidate

    def put(self, storage_key: str, payload: bytes) -> None:
        path = self._resolve(storage_key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Written to a temporary name and moved, so a reader never observes a
        # partially written object under its final key.
        tmp = path.with_suffix(".partial")
        tmp.write_bytes(payload)
        tmp.replace(path)

    def get(self, storage_key: str) -> bytes:
        path = self._resolve(storage_key)
        if not path.is_file():
            raise ObjectStoreUnavailable(
                f"object {storage_key!r} is absent from the local store"
            )
        return path.read_bytes()


class ProductionObjectStore:
    """The production interface. Deliberately not implemented here.

    Binding it needs a provider endpoint and a credential, which is
    `GATE_CREDENTIAL_ENTRY`. Until that happens this raises, and the raise is
    the honest answer: the alternative is a deployment that reports uploads as
    working while writing them to a disk that does not outlive the container.
    """

    def put(self, storage_key: str, payload: bytes) -> None:
        raise ObjectStoreUnavailable(
            "no production object store is bound; binding one is "
            "GATE_CREDENTIAL_ENTRY and is not authorised by this lane"
        )

    def get(self, storage_key: str) -> bytes:
        raise ObjectStoreUnavailable(
            "no production object store is bound; binding one is "
            "GATE_CREDENTIAL_ENTRY and is not authorised by this lane"
        )


DOCUMENT_STORE_MODE_ENV_VAR = "PETCARE_DOCUMENT_STORE_MODE"
DOCUMENT_ROOT_ENV_VAR = "PETCARE_DOCUMENT_ROOT"
MODE_LOCAL = "local"
MODE_OBJECT_STORE = "object_store"


def build_document_store(environ: dict | None = None) -> DocumentStore:
    """The configured store. Unset and unknown both fail closed.

    Mirrors `current_persistence_mode`: an unset mode is not assumed to be the
    weaker one, because the deployment that forgot the variable is exactly the
    deployment that believed its uploads were durable.
    """
    env = environ if environ is not None else os.environ
    mode = (env.get(DOCUMENT_STORE_MODE_ENV_VAR) or "").strip()
    if not mode:
        raise ObjectStoreUnavailable(
            f"{DOCUMENT_STORE_MODE_ENV_VAR} is not set; the document store must "
            f"be chosen explicitly (one of ['{MODE_LOCAL}', "
            f"'{MODE_OBJECT_STORE}'])"
        )
    if mode == MODE_LOCAL:
        root = env.get(DOCUMENT_ROOT_ENV_VAR)
        if not root:
            raise ObjectStoreUnavailable(
                f"{DOCUMENT_STORE_MODE_ENV_VAR}={MODE_LOCAL} requires "
                f"{DOCUMENT_ROOT_ENV_VAR}"
            )
        return LocalFilesystemDocumentStore(root)
    if mode == MODE_OBJECT_STORE:
        return ProductionObjectStore()
    raise ObjectStoreUnavailable(
        f"{DOCUMENT_STORE_MODE_ENV_VAR}={mode!r} is not a known document store "
        "mode; failing closed rather than picking one"
    )
