#!/usr/bin/env python3
"""
DEPRECATED (PH66)

This patch tool was used in PH63 to operationalize quorum by appending entries.
As of PH65, the verification index is deterministically generated by:
  scripts/petcare_verification_index_generate.py
and CI enforces generator-only path via a drift gate.

This tool is retained for EMERGENCY MANUAL RECOVERY ONLY and MUST NOT be used in CI.

Behavior:
- Refuses to run unless --i_know_what_im_doing is provided.
- If CI environment detected, hard fails even with override.

Exit codes:
- 66: deprecated / refused
"""
from __future__ import annotations

import argparse
import os
import sys

EXIT_REFUSE = 66

def main() -> None:
    ap = argparse.ArgumentParser(description="DEPRECATED: patch quorum tool (emergency manual only).")
    ap.add_argument("--i_know_what_im_doing", action="store_true", help="Required override to run (manual only).")
    args, _ = ap.parse_known_args()

    # CI hard refuse (no guessing): common CI env vars
    for k in ("CI", "GITHUB_ACTIONS", "BUILD_NUMBER", "RUN_ID"):
        if os.environ.get(k):
            print("FATAL: deprecated patch tool is forbidden in CI environments.", file=sys.stderr)
            sys.exit(EXIT_REFUSE)

    if not args.i_know_what_im_doing:
        print("FATAL: deprecated tool. Use scripts/petcare_verification_index_generate.py instead.", file=sys.stderr)
        print("If you are doing emergency manual recovery, rerun with --i_know_what_im_doing.", file=sys.stderr)
        sys.exit(EXIT_REFUSE)

    print("FATAL: deprecated tool invoked with override, but PH66 intentionally provides no patch implementation.")
    print("Use the deterministic generator and commit the generated index.")
    sys.exit(EXIT_REFUSE)

if __name__ == "__main__":
    main()
