import { useEffect, useState } from "react";
import { ArrowLeft, FileText, Download, ExternalLink } from "lucide-react";
import { Link } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import api from "../lib/api";

export default function Report() {
  const [markdown, setMarkdown] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await api.getDay3Report();
        setMarkdown(res.data);
      } catch (err) {
        console.error("Error fetching report:", err);
        setError("Failed to load report");
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64" data-testid="report-loading">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-slate-900"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12" data-testid="report-error">
        <FileText className="w-12 h-12 text-slate-300 mx-auto" />
        <p className="mt-4 text-slate-500">{error}</p>
        <Link 
          to="/governance" 
          className="mt-4 inline-flex items-center gap-2 text-sm text-slate-600 hover:text-slate-900"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Governance
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in" data-testid="report-page">
      {/* Back Link */}
      <Link 
        to="/governance" 
        className="inline-flex items-center gap-2 text-sm text-slate-600 hover:text-slate-900"
        data-testid="back-to-governance"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Governance
      </Link>

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight" style={{ fontFamily: 'Manrope, sans-serif' }}>
            Day-3 Analysis Report
          </h1>
          <p className="mt-1 text-slate-500">
            Sprint 6 Day-3 Evidence Analysis Report
          </p>
        </div>
        <div className="flex items-center gap-3">
          <a
            href={`${process.env.REACT_APP_BACKEND_URL}/api/report/day3`}
            download="PetCare_Sprint6_Day3_Evidence_Analysis_Report.md"
            className="inline-flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
            data-testid="download-report"
          >
            <Download className="w-4 h-4" />
            Download MD
          </a>
        </div>
      </div>

      {/* Report Content */}
      <div className="bg-white border border-slate-200 rounded-xl shadow-sm">
        <div className="px-8 py-6 border-b border-slate-200 bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-slate-900 rounded-lg flex items-center justify-center">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="font-semibold text-slate-900">PetCare_Sprint6_Day3_Evidence_Analysis_Report.md</p>
              <p className="text-xs text-slate-500">Generated by Emergent AI Analysis Engine</p>
            </div>
          </div>
        </div>
        <div className="p-8 md:p-12 max-w-4xl mx-auto">
          <article className="prose-report" data-testid="report-content">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{
                h1: ({ children }) => (
                  <h1 className="text-3xl font-bold text-slate-900 mb-6 pb-4 border-b border-slate-200">
                    {children}
                  </h1>
                ),
                h2: ({ children }) => (
                  <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">
                    {children}
                  </h2>
                ),
                h3: ({ children }) => (
                  <h3 className="text-xl font-semibold text-slate-800 mt-8 mb-3">
                    {children}
                  </h3>
                ),
                h4: ({ children }) => (
                  <h4 className="text-lg font-semibold text-slate-700 mt-6 mb-2">
                    {children}
                  </h4>
                ),
                p: ({ children }) => (
                  <p className="text-slate-600 leading-relaxed mb-4">
                    {children}
                  </p>
                ),
                ul: ({ children }) => (
                  <ul className="ml-6 mb-4 space-y-2 list-disc">
                    {children}
                  </ul>
                ),
                ol: ({ children }) => (
                  <ol className="ml-6 mb-4 space-y-2 list-decimal">
                    {children}
                  </ol>
                ),
                li: ({ children }) => (
                  <li className="text-slate-600">
                    {children}
                  </li>
                ),
                code: ({ inline, children }) => 
                  inline ? (
                    <code className="bg-slate-100 text-slate-800 px-1.5 py-0.5 rounded text-sm font-mono">
                      {children}
                    </code>
                  ) : (
                    <code className="block bg-slate-900 text-slate-100 p-4 rounded-lg overflow-x-auto mb-4 font-mono text-sm">
                      {children}
                    </code>
                  ),
                pre: ({ children }) => (
                  <pre className="bg-slate-900 text-slate-100 p-4 rounded-lg overflow-x-auto mb-4">
                    {children}
                  </pre>
                ),
                table: ({ children }) => (
                  <div className="overflow-x-auto mb-6">
                    <table className="w-full border-collapse">
                      {children}
                    </table>
                  </div>
                ),
                thead: ({ children }) => (
                  <thead className="bg-slate-50">
                    {children}
                  </thead>
                ),
                th: ({ children }) => (
                  <th className="text-left text-xs font-medium text-slate-500 uppercase tracking-wider px-4 py-3 border border-slate-200">
                    {children}
                  </th>
                ),
                td: ({ children }) => (
                  <td className="px-4 py-3 text-sm text-slate-700 border border-slate-200">
                    {children}
                  </td>
                ),
                blockquote: ({ children }) => (
                  <blockquote className="border-l-4 border-slate-300 pl-4 italic text-slate-600 my-4">
                    {children}
                  </blockquote>
                ),
                hr: () => (
                  <hr className="border-slate-200 my-8" />
                ),
                strong: ({ children }) => (
                  <strong className="font-semibold text-slate-900">
                    {children}
                  </strong>
                ),
                a: ({ href, children }) => (
                  <a 
                    href={href} 
                    className="text-slate-900 underline hover:text-slate-600 inline-flex items-center gap-1"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    {children}
                    <ExternalLink className="w-3 h-3" />
                  </a>
                ),
              }}
            >
              {markdown}
            </ReactMarkdown>
          </article>
        </div>
      </div>

      {/* Footer Note */}
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-6 text-center">
        <p className="text-sm text-slate-600">
          <span className="font-medium text-slate-900">PetCare is a standalone project.</span>
          {" "}No portfolio/Crédito artifacts are included.
        </p>
      </div>
    </div>
  );
}
